# Generated by Django 4.1.1 on 2022-09-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='redistodo',
        ),
    ]
